<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Envío de Formulario Sin título 8',
	'heading' => 'Envío de nuevo formulario',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Marcada',
		'checkbox_unchecked' => 'No marcada',
		'submitted_from' => 'Formulario enviado desde el sitio web: %s',
		'submitted_by' => 'Dirección IP del visitante: %s',
		'too_many_submissions' => 'Se han realizado recientemente demasiados envíos a través de esta IP',
		'failed_to_send_email' => 'Error al enviar el correo electrónico',
		'invalid_reCAPTCHA_private_key' => 'Clave privada de reCAPTCHA no válida.',
		'invalid_reCAPTCHA2_private_key' => 'Clave privada de reCAPTCHA 2.0 no válida.',
		'invalid_reCAPTCHA2_server_response' => 'Respuesta de servidor de reCAPTCHA 2.0 no válida.',
		'invalid_field_type' => 'Tipo de campo desconocido: %s.',
		'invalid_form_config' => 'El campo \'%s\' contiene una configuración no válida.',
		'unknown_method' => 'Método de solicitud de servidor desconocido'
	),
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'custom_U3144' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Numero de estilo',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Numero de estilo\' es obligatorio.'
			)
		),
		'Email' => array(
			'order' => 3,
			'type' => 'email',
			'label' => 'Correo electrónico',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Correo electrónico\' es obligatorio.',
				'format' => 'El campo \'Correo electrónico\' contiene un correo electrónico no válido.'
			)
		),
		'custom_U3122' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Cantidad de productos',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Cantidad de productos\' es obligatorio.'
			)
		),
		'custom_U3118' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nombre',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Nombre\' es obligatorio.'
			)
		),
		'custom_U3139' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Ciudad',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Ciudad\' es obligatorio.'
			)
		),
		'custom_U3114' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Región',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Región\' es obligatorio.'
			)
		),
		'custom_U3131' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Código postal',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Código postal\' es obligatorio.'
			)
		),
		'custom_U3127' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Tarjeta debito/credito',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Tarjeta debito/credito\' es obligatorio.'
			)
		),
		'custom_U3135' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Numero de tarjeta',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Numero de tarjeta\' es obligatorio.'
			)
		),
		'custom_U3239' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'MM/AA',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'MM/AA\' es obligatorio.'
			)
		),
		'custom_U3440' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'CVC',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'CVC\' es obligatorio.'
			)
		)
	)
);

process_form($form);
?>
